# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92e63b210bf343736c15d460f43838aaecd42f64e43e8177d154e232f0d5c64f19f42f1bd030e552b661a8cb369cf90624f4f3e474ba26022c0e9199ca9ac0bc

test:
  secret_key_base: 230d4750195ebf6dd4ef0b78dbcd6adf120816bd1a960bfca0c71c7a64686f3a78a19af8c2c2b29b146349537115e27317da88c5ad4b9bef69b55c2e5cce3a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
